'''Standard values used all throughout the program.'''
MIN_NAME_LEN_FIRST = 1
MAX_NAME_LEN_FIRST = 50
MIN_NAME_LEN_LAST = 1
MAX_NAME_LEN_LAST = 50

MIN_LEN_HANDLE = 3
MAX_LEN_HANDLE = 20

MIN_PASSWORD_LEN = 6

MIN_NAME_LEN_CHANNEL = 1
MAX_NAME_LEN_CHANNEL = 20

GLOBAL_OWNER_PERM = 1
MEMBER_PERM = 2
VALID_PERMS = [GLOBAL_OWNER_PERM, MEMBER_PERM]